//
//  CompanyDetailRouter.swift
//  MediquoApp
//
//  Created by Guillem Espejo on 05/11/2020.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

import UIKit

@objc protocol CompanyDetailRoutingLogic{
    func routeToErrorAlert(_ error:Error)
}

protocol CompanyDetailDataPassing{
    var dataStore: CompanyDetailDataStore? { get }
}

class CompanyDetailRouter: NSObject, CompanyDetailRoutingLogic, CompanyDetailDataPassing{
    // MARK: - Attributes
    weak var viewController: CompanyDetailViewController?
    var dataStore: CompanyDetailDataStore?
    
    // ------------------------------------------------------------
    // INIT-DEINIT
    // ------------------------------------------------------------
    // MARK: - Init-Deinit
    init(viewController: CompanyDetailViewController? , dataStore: CompanyDetailDataStore?) {
        self.viewController = viewController
        self.dataStore = dataStore
    }
  
    // ------------------------------------------------------------
    // ROUTING
    // ------------------------------------------------------------
    // MARK: - Routing
    func routeToErrorAlert(_ error: Error){        
        let alertController = UIAlertController.createWith(error)
        viewController?.present(alertController, animated: true, completion: nil)
    }

    // ------------------------------------------------------------
    // NAVIGATION MANAGEMENT
    // ------------------------------------------------------------
    // MARK: - Navigation Management
//    private func navigateToSomewhere(source: CompanyDetailViewController, destination: SomewhereViewController){
//        source.show(destination, sender: nil)
//    }

    // ------------------------------------------------------------
    // DATA PASSING
    // ------------------------------------------------------------
    // MARK: - Data Passing
//    private func passDataToSomewhere(source: CompanyDetailDataStore, destination: inout SomewhereDataStore){
//        destination.name = source.name
//    }
}
