//
//  CompanyDetailWorker.swift
//  MediquoApp
//
//  Created by Guillem Espejo on 05/11/2020.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

import UIKit

class CompanyDetailWorker{
    
    var dataStore : StationStoreAPI
    
    init(dataStore: StationStoreAPI = StationStoreSync() ){
        self.dataStore = dataStore
    }
    
    func loadStations(from network: Network ,completion: @escaping (Result<[Station],Error>) -> Void ){
        self.dataStore.getStations(from: network, completion: completion)
    }
}
