//
//  CompanyListPresenterTests.swift
//  MediquoApp
//
//  Created by Guillem Espejo on 07/11/2020.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

@testable import MediquoApp
import XCTest

class CompanyListPresenterTests: XCTestCase{
	
    // MARK: Subject under test
    var sut: CompanyListPresenter!

    override func setUp(){
        super.setUp()
        setupCompanyListPresenter()
    }
  
    override func tearDown(){
        super.tearDown()
    }
  
	// ------------------------------------------------------------
	// TEST SETUP
	// ------------------------------------------------------------
	// MARK: - Test Setup
    func setupCompanyListPresenter(){
        sut = CompanyListPresenter(viewController: nil)
    }
  
	// ------------------------------------------------------------
	// TESTS
	// ------------------------------------------------------------
	// MARK: - Tests
    func testPresentBaseNetworkData(){
        // Given
        let spy = CompanyListDisplayLogicSpy()
        sut.viewController = spy
        
        let companyA = Company(fromString: "BBB" + Constants.CoreData.CompanyStringSeparator + "AAA" + Constants.CoreData.CompanyStringSeparator)
        let fakeLocation = Location(city:"TEST",country:"TEST",latitude:0.1,longitude:01)
        let network = Network(company:companyA, href:"SAME", id:"1", location:fakeLocation, name:"TEST")

        let response = CompanyList.LoadBaseNetworkData.Response(networks: [network])

        // When
        sut.presentBaseNetworkData(response: response)

        // Then
        XCTAssertTrue(spy.displayBaseNetworkWasCalled, "presentBaseNetworkData(response:) should ask the view controller to display the result")
        XCTAssertEqual(spy.displayableList.count, 2,
                       "presentBaseNetworkData(response:) should have created two entries from a single network")
        XCTAssertEqual(spy.displayableList.first!.companyName, "AAA",
                       "presentBaseNetworkData(response:) did sort in wrong order")
        XCTAssertEqual(spy.displayableList.last!.companyName, "BBB",
                       "presentBaseNetworkData(response:) did sort in wrong order")
    }
    
    func testPresentBaseNetworkError(){
        // Given
        let spy = CompanyListDisplayLogicSpy()
        sut.viewController = spy
      
        // When
        sut.presentBaseNetworkDataError(MediquoError.coreDataStackError)

        // Then
        XCTAssertTrue(spy.displayBaseNetworkErrorWasCalled, "presentBaseNetworkDataError(error:) should ask the view controller to display an error")
    }
}
