//
//  CompanyListRouter.swift
//  MediquoApp
//
//  Created by Guillem Espejo on 05/11/2020.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

import UIKit

@objc protocol CompanyListRoutingLogic{
    func routeToShowCompany(segue: UIStoryboardSegue?)
    func routeToErrorAlert(_ error:Error)
}

protocol CompanyListDataPassing{
    var dataStore: CompanyListDataStore? { get }
}

class CompanyListRouter: NSObject, CompanyListRoutingLogic, CompanyListDataPassing{
    // MARK: - Attributes
    weak var viewController: CompanyListViewController?
    var dataStore: CompanyListDataStore?
    
    // ------------------------------------------------------------
    // INIT-DEINIT
    // ------------------------------------------------------------
    // MARK: - Init-Deinit
    init(viewController: CompanyListViewController? , dataStore: CompanyListDataStore?) {
        self.viewController = viewController
        self.dataStore = dataStore
    }
  
    // ------------------------------------------------------------
    // ROUTING
    // ------------------------------------------------------------
    // MARK: - Routing
    func routeToShowCompany(segue: UIStoryboardSegue?){
        if let segue = segue {
            guard let navController = segue.destination as? UINavigationController else{
                print("ERROR: Destination is not a NAVIGATIONCONTROLLER, did you change the VC hiearchy?")
                return
            }
            
            guard let detailController = navController.viewControllers.first as? CompanyDetailViewController else{
                print("ERROR: There is no VC in the NavigationController, did you change the VC hiearchy?")
                return
            }
            
            var destinationDS = detailController.router!.dataStore!
            passDataToCompanyDetail(source: dataStore!, destination: &destinationDS)
        }
        // Extend with a non-segue way if needed, use the 'navigateToSomeWhere' pattern
    }
    
    func routeToErrorAlert(_ error: Error){
        let alertController = UIAlertController.createWith(error)
        viewController?.present(alertController, animated: true, completion: nil)
    }
    

    // ------------------------------------------------------------
    // NAVIGATION MANAGEMENT
    // ------------------------------------------------------------
    // MARK: - Navigation Management
//    private func navigateToSomewhere(source: CompanyListViewController, destination: SomewhereViewController){
//        source.show(destination, sender: nil)
//    }

    // ------------------------------------------------------------
    // DATA PASSING
    // ------------------------------------------------------------
    // MARK: - Data Passing
    private func passDataToCompanyDetail(source: CompanyListDataStore, destination: inout CompanyDetailDataStore){
        
        guard let indexPath = self.viewController?.tableViewCompanies.indexPathForSelectedRow else{
            print("ERROR: There is no VC in the NavigationController, did you change the VC hiearchy?")
            return
        }
        
        let displayable = self.viewController?.filteredDisplayableCompanies[indexPath.row]
        
        let finalNetwork = source.networkList.first { (network) -> Bool in
            return network.id == displayable?.originalId
        }
    
        destination.companyName = displayable?.companyName
        destination.network = finalNetwork
    }
}
