//
//  CompanyListModels.swift
//  MediquoApp
//
//  Created by Guillem Espejo on 05/11/2020.
//
//  This file was generated by the Guillem Espejo Clean Swift Xcode Templates
//

import UIKit

enum CompanyList {
	
	// ------------------------------------------------------------
	// DISPLAYABLES
	// ------------------------------------------------------------
	// MARK: - Displayables
    struct DisplayableCompany : Hashable{
		var companyName : String
        var networkName : String
        var originalId : String
	}

	// ------------------------------------------------------------
	// USE CASES
	// ------------------------------------------------------------
	// MARK: - Use cases
    enum LoadBaseNetworkData {
        struct Request {
            
        }
        
        struct Response {
            var networks : [Network]
        }
        
        struct ViewModel {
            var companyList : [DisplayableCompany]
        }
    }
}
